'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contact

    '''<summary>
    '''ltUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltUsername As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''profileCompletionDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profileCompletionDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Addaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Addaddress As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''weather control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents weather As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''UserCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserCity As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SubscriptionCustomerStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriptionCustomerStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SubsChoose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubsChoose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblFirstSubscriptionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstSubscriptionName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblFirstSubscriptionPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstSubscriptionPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSecondSubscriptionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondSubscriptionName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSecondSubscriptionPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondSubscriptionPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblThirdSubscriptionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThirdSubscriptionName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblThirdSubscriptionPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThirdSubscriptionPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFourthSubscriptionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFourthSubscriptionName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFourthSubscriptionPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFourthSubscriptionPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFifthSubscriptionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFifthSubscriptionName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFifthSubscriptionPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFifthSubscriptionPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSixthSubscriptionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSixthSubscriptionName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSixthSubscriptionPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSixthSubscriptionPrice As Global.System.Web.UI.WebControls.Label
End Class
